## ya lo estudie ##

# Versión del formato de CloudFormation template
AWSTemplateFormatVersion: '2010-09-09'
# Transform indica que este template usa AWS SAM (Serverless Application Model)
Transform: AWS::Serverless-2016-10-31

# Parámetros que se solicitan durante el despliegue
Parameters:
  BlueDragonURL:
    Type: String  # URL del API externo de terceros al que se enviarán los eventos
  BlueDragonApiKeyHeaderName:
    Type: String
    Default: x-api-key
    Description: Nombre del header donde se enviará la API key
  BlueDragonApiKeySecretName:
    Type: String
    Description: Nombre o ARN del secreto en Secrets Manager que contiene la API key
  BlueDragonApiKeySecretKey:
    Type: String
    Default: apiKey
    Description: Clave JSON dentro del SecretString donde se guarda la API key

Resources:

  # Conexión para autenticación con el API externo
  BlueDragonConnection:
    Type: AWS::Events::Connection
    Properties:
      AuthorizationType: API_KEY  # Tipo de autenticación: API Key
      Description: Connection with an API key
      AuthParameters:
        ApiKeyAuthParameters:
          ApiKeyName: !Ref BlueDragonApiKeyHeaderName  # Nombre del header real (p. ej., x-api-key)
          # Referencia dinámica a Secrets Manager; espera un SecretString con la clave JSON indicada
          ApiKeyValue: !Sub "{{resolve:secretsmanager:${BlueDragonApiKeySecretName}:SecretString:${BlueDragonApiKeySecretKey}}}"

  # API Destination: configuración del endpoint HTTP que EventBridge invocará
  BlueDragonApiDestination:
    Type: AWS::Events::ApiDestination
    Properties:
      Name: BlueDragonApiDestination
      ConnectionArn: !GetAtt BlueDragonConnection.Arn  # Referencia a la conexión de autenticación creada arriba
      InvocationEndpoint: !Ref BlueDragonURL  # URL del endpoint (viene del parámetro)
      HttpMethod: POST  # Método HTTP a usar para invocar el API
      InvocationRateLimitPerSecond: 10  # Límite de invocaciones por segundo (throttling)

  # Regla de EventBridge que filtra eventos y los envía al API Destination
  BlueDragonEventRule:
    Type: AWS::Events::Rule
    Properties:
      Description: BlueDragon EventRule
      EventPattern:  # Patrón para filtrar qué eventos activarán esta regla
        source:
          - custom.orderManager  # Solo eventos del servicio orderManager
        detail-type:
          - order  # Solo eventos de tipo "order"
        detail:
          restaurantName:
            - blueDragon  # Solo órdenes para el restaurante "blueDragon"
      Targets:  # A dónde se envían los eventos que coinciden con el patrón
        - Arn: !GetAtt BlueDragonApiDestination.Arn  # ARN del API Destination
          RoleArn: !GetAtt EventBridgeTargetRole.Arn  # Rol IAM que permite invocar el API
          Id: BlueDragonApiDestination  # Identificador único del target

  # Rol IAM que otorga permisos a EventBridge para invocar el API Destination
  EventBridgeTargetRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:  # Define quién puede asumir este rol
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - events.amazonaws.com  # El servicio EventBridge puede asumir este rol
            Action:
              - sts:AssumeRole  # Acción para asumir el rol
      Policies:  # Políticas asociadas al rol
        - PolicyName: AllowAPIdestinationAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: events:InvokeApiDestination  # Permiso para invocar API Destinations
                Resource: !GetAtt BlueDragonApiDestination.Arn  # Solo puede invocar este API Destination específico

## ya lo estudie ##